### PR TITLE
Readd updated recorded recommendations

### PR DESCRIPTION
**Pull request by jrapin**

### CODE REVIEW

**Comment by jrapin** [comment]
You should be able to merge this directly and it will update your PR on the main repo

**Comment by ljialin** [comment]
Dear Jérémy,

Thank you for your help!
I got 23 failures even after running twice pytest nevergrad/optimization/test_optimizerlib.py
According to the output log, All the failures were due to the assertions of tell and ask when testing EDA variants (I guess so). I’m not very familiar with the code.
Could you please kindly give me some hints? Attached please find the log file.

Best,
Jialin
[error.log](https://github.com/ljialin/nevergrad/files/4004419/error.log)

**Comment by ljialin** [comment]
> You should be able to merge this directly and it will update your PR on the main repo

Dear Jérémy,

Thank you for your help!
I got 23 failures even after running twice pytest nevergrad/optimization/test_optimizerlib.py
According to the output log, All the failures were due to the assertions of tell and ask when testing EDA variants (I guess so). I’m not very familiar with the code.
Could you please kindly give me some hints? Attached please find the log file.

Best,
Jialin
[error.log](https://github.com/ljialin/nevergrad/files/4004422/error.log)

**Comment by jrapin** [comment]
This is now fixed (see https://github.com/facebookresearch/nevergrad/pull/383#pullrequestreview-336707495), the root cause was a wrong indent that the PR was adding in `test_optimizerlib.py`

**Pull request merged**
